[project]
name = "practice4"
authors = []
description = ""
telemetry = true
requirements = []
boot_contracts = ["pox", "costs-v2", "bns"]

[project.cache_location]
path = ".requirements"
[contracts.cargo]
path = "contracts/cargo.clar"

[contracts.divider-trait]
path = "contracts/divider-trait.clar"

[contracts.functions]
path = "contracts/functions.clar"

[contracts.math]
path = "contracts/math.clar"

[contracts.multiplier-trait]
path = "contracts/multiplier-trait.clar"

[contracts.storing-data]
path = "contracts/storing-data.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
